# Change these first
owner: ti-or # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: 1PTBar
    url: $N1PTBAR
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/1ptba.ico
    maxResponseTime: 1000
  - name: 52PT
    url: $N52PT
    maxResponseTime: 1000
  - name: AGSV
    url: $AGSV
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/agsv.ico
    maxResponseTime: 1000
  - name: Audiences
    url: $AUDIENCES
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/audiences.ico
    maxResponseTime: 1000
    expectedStatusCodes:
      - 403
  - name: BTSCHOOL
    url: $BTSCHOOL
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/bts.ico
    maxResponseTime: 1000
  - name: CarPT
    url: $CARPT
    maxResponseTime: 1000
  - name: CHDBits
    url: $CHDBITS
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/chdbits.ico
    maxResponseTime: 1000
  - name: CyanBug
    url: $CYANBUG
    maxResponseTime: 1000
  - name: DIC
    url: $DIC
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/dic.ico
    maxResponseTime: 1000
  - name: DiscFan
    url: $DISCFAN
    maxResponseTime: 1000
  - name: FSM
    url: $FSM
    maxResponseTime: 1000
  - name: GGPT
    url: $GGPT
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/ggpt.ico
    maxResponseTime: 1000
  - name: GPW
    url: $GPW
    maxResponseTime: 1000
  - name: HaresClub
    url: $HARESCLUB
    maxResponseTime: 1000
  - name: HD Dolby
    url: $HDDOLBY
    maxResponseTime: 1000
    expectedStatusCodes:
      - 403
  - name: HD4FANS
    url: $HD4FANS
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/hd4fans.ico
    maxResponseTime: 1000
  - name: HDATMOS
    url: $HDATMOS
    maxResponseTime: 1000
  - name: HDCity
    url: $HDCITY
    maxResponseTime: 1000
  - name: HDHome
    url: $HDHOME
    maxResponseTime: 1000
    expectedStatusCodes:
      - 403
  - name: HDFans
    url: $HDFANS
    maxResponseTime: 1000
  - name: HDSky
    url: $HDSKY
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/hdsky.ico
    maxResponseTime: 1000
  - name: HDKylin-麒麟
    url: $HDKYLIN
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/kylin.ico
    maxResponseTime: 1000
  - name: HDPOST
    url: $HDPOST
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/hdpost.ico
    maxResponseTime: 1000
  - name: M-Team
    url: $MTEAM
    maxResponseTime: 1000
  - name: PT@KEEPFRDS
    url: $KEEPFRDS
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/frds.ico
    maxResponseTime: 1000
  - name: PTChina
    url: $PTCHINA
    maxResponseTime: 1000
  - name: PTer
    url: $PTER
    maxResponseTime: 1000
  - name: pttime
    url: $PTTIME
    maxResponseTime: 1000
    expectedStatusCodes:
      - 403
  - name: Rousi
    url: $ROUSI
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/rousi.ico
    maxResponseTime: 1000
  - name: SSD
    url: $SSD
    maxResponseTime: 1000
  - name: ToSky
    url: $TOSKY
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/tosky.ico
    maxResponseTime: 1000
  - name: UltraHD
    url: $ULTRAHD
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/ultrahd.ico
    maxResponseTime: 1000
  - name: U2
    url: $U2
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/u2.ico
    maxResponseTime: 1000
  - name: UBits
    url: $UBITS
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/ubits.ico
    maxResponseTime: 1000
  - name: wintersakura
    url: $WINTERSAKURA
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/sakura.ico
    maxResponseTime: 1000
  - name: ZHUQUE
    url: $ZHUQUE
    maxResponseTime: 1000
  - name: ZmPT(织梦)
    url: $ZMPT
    maxResponseTime: 1000
  - name: 蟹黄堡
    url: $CRABPT
    maxResponseTime: 1000
  - name: 明教
    url: $HDPT
    maxResponseTime: 1000
  - name: 杏坛
    url: $XINGTAN
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/xingtan.ico
    maxResponseTime: 1000

status-website:
  workflowSchedule:
    uptime: "0 */1 * * *"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: light
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
