# Change these first
owner: ti-or # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: 1PTBar
    url: $N1PTBAR
    icon: 1ptba.ico
    maxResponseTime: 1000
  - name: 52PT
    url: $N52PT
    maxResponseTime: 1000
  - name: Audiences
    url: $AUDIENCES
    icon: audiences.ico
    maxResponseTime: 1000
    expectedStatusCodes:
      - 403
  - name: CarPT
    url: $CARPT
    maxResponseTime: 1000
  - name: CyanBug
    url: $CYANBUG
    maxResponseTime: 1000
  - name: DAJIAO
    url: $DAJIAO
    maxResponseTime: 1000
  - name: DIC
    url: $DIC
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/dic.ico
    maxResponseTime: 1000
  - name: DiscFan
    url: $DISCFAN
    maxResponseTime: 1000
  - name: FSM
    url: $FSM
    maxResponseTime: 1000
  - name: GPW
    url: $GPW
    maxResponseTime: 1000
  - name: HaresClub
    url: $HARESCLUB
    maxResponseTime: 1000
  - name: HD Dolby
    url: $HDDOLBY
    maxResponseTime: 1000
    expectedStatusCodes:
      - 403
  - name: HDHome
    url: $HDHOME
    maxResponseTime: 1000
    expectedStatusCodes:
      - 403
  - name: HDCity
    url: $HDCITY
    maxResponseTime: 1000
  - name: HDATMOS
    url: $HDATMOS
    maxResponseTime: 1000
  - name: HDFans
    url: $HDFANS
    maxResponseTime: 1000
  - name: HDPT
    url: $HDPT
    maxResponseTime: 1000
  - name: HDSky
    url: $HDSKY
    icon: https://raw.githubusercontent.com/ti-or/status/master/assets/hdsky.ico
    maxResponseTime: 1000
  - name: M-Team
    url: $MTEAM
    maxResponseTime: 1000
  - name: OpenCD
    url: $OPENCD
    maxResponseTime: 1000
  - name: pttime
    url: $PTTIME
    maxResponseTime: 1000
  - name: PTChina
    url: $PTCHINA
    maxResponseTime: 1000
  - name: PTer
    url: $PTER
    maxResponseTime: 1000
  - name: SSD
    url: $SSD
    maxResponseTime: 1000
  - name: ZHUQUE
    url: $ZHUQUE
    maxResponseTime: 1000
  - name: ZmPT
    url: $ZMPT
    maxResponseTime: 1000
  - name: crabpt
    url: $CRABPT
    maxResponseTime: 1000

status-website:
  workflowSchedule:
    uptime: "0 */1 * * *"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: light
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
